### ISSUE TITLE
wrong url for localization project

### ISSUE THREAD

**Issue by trendspotter** [mainio/decidim-module-tags#1]
Hi, 
the URL https://crowdin.com/project/decidim-access-requests is not relevant to "Tags module" localization project. Do You have a plan enable it on Crowdin? 

Thank You

**Comment by ahukkanen** [comment]
The Crowdin repository is now setup and can be found from:
https://crowdin.com/project/decidim-tags

**Comment by trendspotter** [comment]
thanks :) Please enable Czech language

**Comment by ahukkanen** [comment]
> thanks :) Please enable Czech language

Added Czech.
